obj-$(CONFIG_ARCH_MXS)				+= lcdif.o
obj-$(CONFIG_FB_MXS)				+= mxsfb.o
obj-$(CONFIG_FB_MXS_LCD_43WVF1G)		+= lcd_43wvf1g.o
obj-$(CONFIG_FB_MXS_LCD_LMS430)			+= lcd_lms430.o
obj-$(CONFIG_FB_MXS_LCD_FG0700)			+= lcd_fg0700.o
obj-$(CONFIG_FB_MXS_LCD_ETQ570G0DH6)		+= lcd_etq570g0dh6.o

# TVOUT support
obj-$(CONFIG_FB_MXS_TVENC)			+= tvenc.o
